######################################################################
# Automatically generated by qmake (3.0) ter dez 13 12:28:58 2016
######################################################################

QT += quick qml
TEMPLATE = app
TARGET = calculator
INCLUDEPATH += .

# Input
SOURCES += main.cpp
RESOURCES += calqlatr.qrc
